# The URL the site will be built for
base_url = "https://blog.stdin.in"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

theme = "hook"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
title = "owl's Blog"
description = "owl's Blog"
generate_feed = true

[markdown]

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "agola-dark"

[extra]

links = [
    { title = "Github", href = "https://github.com/oowl" },
    { title = "Email", href = "mailto:ouyangjun1999@gmail.com" },
    { title = "RSS", href = "https://blog.stdin.in/atom.xml" },
    { title = "Mastodon", href = "https://mastodon.social/@oowl" },
    { title = "Travel", href = "/travel" },
    # ...
]
# Put all your custom variables here
